#!/bin/sh
PHPCS_BIN=./vendor/squizlabs/php_codesniffer/scripts/phpcs
PHPCS_CODING_STANDARD=./shell/git/hooks/psr_rules.xml
PHPCS_IGNORE="*.json,*.lock,*.xml,*.yaml,*.md,*.js,*.css,*.html,*.sh,*.txt,*.ico"
PHPCS_FILE_PATTERN="src|app|lib|web"
